import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Header from "./components/header";
import Head from "next/head"; // Asegúrate de importar Head

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DanieloPortFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Head>
        {/* Metaetiqueta de verificación de Google */}
        <meta
          name="google-site-verification"
          content="sNdwOQ0S-7L3YeMAFopXjZIIf83vKNYKUyRR3o50_08"
        />
      </Head>
      <body className={urbanist.className}>
        <Navbar />
        <Header />
        {children}
      </body>
    </html>
  );
}
